### ISSUE TITLE
SSK rules are not correct

### ISSUE THREAD

**Issue by Jopyth** [knub/onehundredandtwenty#27]
You can only use exactly 6 points from the SSK-MA category, not more. Currently it is possible to satisfy the Softskills rule with for example 9 points from SSK-MA, 6 points from SSK-KO, and 3 points SSK-RE.

> In  der  Modulgruppe  Softskills  (SSK)  ist  das  Pflichtmodul  Softskills:  Management  (SSK-MA)  mit  6  LP  zu erbringen.

**Comment by psieg** [comment]
It depends on how you read these sentences. It always says something along the lines of "zu erbringen", but I assume making more points than necessary is no problem.
Thus it would only be an error if you cold satisfy the second part of the rule ("Weiter müssen in der Modulgruppe Softskills 12 LP erworben werden...") with a set of courses as you describe (6 SSK-KO and 3 SSK-RE + any courses with SSK-MA only). I failed to reproduce a such combination. Note some SSK-MA courses can also be used towards SSK-KO or SSK-RE.

Can you produce a such combination?

**Comment by knub** [comment]
I think @Jopyth is right. You are not allowed to do more than 6 LP in SSK-MA (atleast it does not count towards the degree then).
Doing 9 LP in SSK-MA can be achieved by taking "Fuehrungskompetenz" and "Management Essentials", which are both SSK-MA only. Even if such a combination were not possible so far, it might be in the future.
The rule is not implemented correctly.

**Comment by psieg** [comment]
I'm afraid I don't understand the issue. You can achieve 9 LP with the one courses named above, but how is that a problem. Those points are not counted towards the "rest" as far as I know and having 9 instead of 6 should not be a problem?

**Comment by knub** [comment]
Ah, I see. So that's what I meant by "it does not count towards your degree" then. So if I do this as above,  the 3LP of Management Essentials are ignored by 120? Correct?
That would be fine then, of course.

**Comment by psieg** [comment]
That's why I was asking for a combination of courses 120 validates but the Studienordnung would not.
I'm 90% sure a course counted towards MA is not counted towards another one

**Comment by Jopyth** [comment]
I think I was mistaken, I was confused by different SSK categories of Personal Management Skills in the different semesters. In WS15/16 it has SSK-MA and SSK-KO, and before it was only SSK-MA, it seems.
