### ISSUE TITLE
Mapping of Vertiefungsgebiete to credit requirement is broken

### ISSUE THREAD

**Issue by flxw** [knub/onehundredandtwenty#28]
As visible in the screenshots, the selected courses account for more than 24 points in BPET and 15 in OSIS. Other combinations are possible as well. Even though this requirement is met, 120 still displays it as being not. I can also provide a data dump of client-side stored information, if necessary.

![screen shot 2015-12-23 at 2 39 11 pm](https://cloud.githubusercontent.com/assets/942398/11971049/64b797e8-a982-11e5-8ad6-8026643a6e76.png)
![screen shot 2015-12-23 at 2 32 44 pm](https://cloud.githubusercontent.com/assets/942398/11971018/b249f8f8-a981-11e5-9661-b2b85af2cf35.png)
<img width="505" alt="screen shot 2015-12-23 at 2 32 58 pm" src="https://cloud.githubusercontent.com/assets/942398/11971019/b24aef6a-a981-11e5-840d-3e3b0d274668.png">

**Comment by psieg** [comment]
Hi,

the error occurs because NUMA does not contribute towards any vaild combination, which triggers this bug (all combinations are dropped). Thanks for reporting.

If you want to confirm the fix, please test by checking out the branch and opening the local index.html with your browser.

Happy Holidays

**Comment by knub** [comment]
Thanks a lot @psieg!

**Comment by knub** [comment]
Coming to think of it, do you think the same problem could exist in 180, or is this 120 specific?

**Comment by psieg** [comment]
I think the affected rule is one I added specifically for the master requirements, so 120 should not be affected
