### ISSUE TITLE
Please add course Einsatz von cloud- und webbasierten Konzepten im schulischen Kontext

### ISSUE THREAD

**Issue by tamslo** [knub/onehundredandtwenty#37]
Link to course page on HPI Website: https://hpi.de/studium/lehrveranstaltungen/it-systems-engineering/lehrveranstaltung/course/0/wintersemester-20162017-einsatz-von-cloud-und-webbasierten-konzepten-im-schulischen-kontext.html

**Comment by knub** [comment]
Please add the course to [`js/data.js`](https://github.com/knub/onehundredandtwenty/blob/master/js/data.js) and open a pull-request.
